name: Actionlint

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

permissions:
  contents: read

jobs:
  actionlint:
    name: Lint GitHub Workflows
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run actionlint
        uses: rhysd/actionlint@v1
